// WARNING: DO NOT EDIT. This file is Auto-Generated by AWS Mobile Hub. It will be overwritten.

// Copyright 2017-2018 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to
// copy, distribute and modify it.

// AWS Mobile Hub Project Constants
const awsmobile = {
    'aws_app_analytics': 'enable',
    'aws_cognito_identity_pool_id': 'us-east-1:2d7e5a85-1fcd-4d7f-9660-f49f85fb3484',
    'aws_cognito_region': 'us-east-1',
    'aws_mobile_analytics_app_id': 'f883eba84b244dc28f787fb8a7dbb545',
    'aws_mobile_analytics_app_region': 'us-east-1',
    'aws_project_id': 'ea6be5ac-ca9d-4423-b719-b83768e5d011',
    'aws_project_name': 'Proost',
    'aws_project_region': 'us-east-1',
    'aws_resource_name_prefix': 'proost-mobilehub-363916083',
    'aws_user_pools': 'enable',
    'aws_user_pools_id': 'us-east-1_IbYIzEezU',
    'aws_user_pools_web_client_id': '2ku8ut30945t2ah7r8phicoop4'
} 

export default awsmobile;
